/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rzkV1VFRsNy
 */

export function Component() {
  return (
    <div className="flex flex-col h-full">
      <div className="flex-1 p-4 overflow-y-auto">
        <div className="flex flex-col gap-4">
          <div className="flex flex-col-reverse">
            <div className="bg-gray-100 p-2 rounded-tl-xl rounded-br-xl max-w-[75%]">
              <p className="text-sm">Hey there!</p>
            </div>
          </div>
          <div className="flex">
            <div className="bg-gray-200 p-2 rounded-tl-xl rounded-br-xl max-w-[75%]">
              <p className="text-sm">Hi! How can I help you today?</p>
            </div>
          </div>
        </div>
      </div>
      <div className="p-4">
        <div className="flex items-center space-x-2">
          <input
            className="flex-1 p-2 rounded-l-full border border-gray-200 focus:outline-none focus:ring focus:ring-gray-300 dark:border-gray-700 dark:focus:ring-gray-600 dark:border-gray-800"
            placeholder="Type your message..."
            type="text"
          />
          <button className="px-4 py-2 bg-gray-900 text-white rounded-r-full hover:bg-gray-800 focus:outline-none focus:ring focus:ring-gray-300 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            Send
          </button>
        </div>
      </div>
    </div>
  );
}
